#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Std;

our($opt_s,$opt_i,$opt_g,$opt_d,$opt_u,$opt_r);
getopt('sigdur');
print "
*****USAGE*****
\nperl Scriptfile_name -options
-s sequencefile containing genomic DNA sequence.
-i spidey_result_file name
-g gene_outputfile file name [optional]
-r summary_output file name [optional]
-d length of sequence to be extracted downstream of the gene [optional]
-u length of sequence to be extracted upstream of the gene [optional]

\n\n";

my (%seq_hash);

# kill the script if $opt_i and $opt_s are not given.

die "Spidey_output_file not found. \nPlease provide output file generated by spidey with flag -i\n\n" if !defined $opt_i;
die "Genomic sequence file not found. \nPlease provide genomic sequence file used for running spidey with flag -s\n\n" if !defined $opt_s ;


if(!defined $opt_g){$opt_g='GENE_spideyParse_'.$opt_i.'.fasta';}
if(!defined $opt_r){$opt_r='SUMMARY_spideyParse_'.$opt_i.'.out';}

my$seqfile=$opt_s;
my$spidey_output_file=$opt_i;
#my$gene_output="$seqfile.gene.out";
#my$summary_output="$seqfile.summary.out";
my$gene_output=$opt_g;
my$summary_output=$opt_r;
my$upstreamsequence= 'Upstream_'.$opt_u.'_bases_'.$opt_i.'.fasta';
my$downstreamsequence='Downstream_'.$opt_d.'_bases_'.$opt_i.'.fasta';



open GENE,">$gene_output" or die "gene_output not defined\n";
open FASTA,"$seqfile" or die "Seqfile not defined\n";
open SUMMARY,">$summary_output" or die "summary_output not defined\n";
open UP,">$upstreamsequence" if defined $opt_u;
open DOWN,">$downstreamsequence" if defined $opt_d;
####################################################################################################
# Read database sequence in to a hash %seq_hash{}, remove ">" from header. 
# remove any white spaces and newline from sequence.

print "reading Sequences from input file.....Plz wait...\n";
$/="\n>";

while(<FASTA>){#
    chomp;
    my($header,@sequence)=split("\n",$_);
    $header=~s/>//;
    $header=~s/\s//g;

    my$sequence= join("",@sequence);
    $sequence=~ s/\s//g;
    $sequence=~s/\n//g;
    #print "$header\n";
    #feed headers and sequences in hash.
    $seq_hash{$header}=$sequence;

    #print "$seq_hash{$header}\n\n";
}#
my @seq_count=keys (%seq_hash);
my $seq_count=@seq_count;

print "Done....\nNumber of sequences read form input file = $seq_count\n\n";
@seq_count=();
############################################################################################

#########################################################################################################
# Parsing the spidey output file
print "reading Spidey out put file.........\n";
spidey_parse($spidey_output_file);











###########################################################################################
# Subroutine for parsing spidey output file for the gene name, co-ordinates of exon and 
# introns.Output table with all the co-ordinates arranged in a nice format.

sub spidey_parse{
open SPIDYOUT,(my$spidey_output= shift(@_));
$/= "\n--SPIDEY";
#print "Spidey output file is:$spidey_output\n";
	my$chunk_number=0;
	while(<SPIDYOUT>){
		$chunk_number++;
		#print "\n\nStart of chunk $chunk_number\n$_\n\nend of chunk\n";
		if($_=~/^\s*$/){next;}
		my ($genomic,$mRNA,$strand,$missing_mRNA_ends,%gene,@mRNA_info,%downstream,%upstream)=();
		my ($exon_N,$splice_site,$mRNA_coverage,%exon_start,%exon_end,%mRNA_start,%mRNA_end,%exon_percent_identity,%exon_gap,$percent_identity,%exon_mismatch)=0;
		my$chunk=$_;
		$chunk=~s/(--SPIDEY\s*version\s[\d\W]*?--)//g;
		$chunk=~s/(--SPIDEY)//g;
		if($chunk=~/(No\s+alignment\s+found)/){next;}

#print "\n\nChunk read is : \n$chunk\n";

		if($chunk=~/(Genomic:[\s\w\d\W\S\D]*?Missing mRNA ends:\s*neither)/){
		$chunk=$1;
		#print"\nprinting Dollar 1:$1\n";
		}  
#print "\n\nSelected chunk is: \n$1\nxxxxxx\n";

		@mRNA_info= split(/\n/,$chunk);  
#print "First line of the chunk is : $mRNA_info[0]\n";			
			
			foreach my$mRNA_info(@mRNA_info){
				
				chomp($mRNA_info);
				
				if($mRNA_info=~/^Genomic:[\s\w]*\|([\.\w\W\|\_\-]*?)\s+([\w\s]*)\,\s*([\d]*)\s*bp/){
				$genomic=$1;
				$genomic=~s/\s//g;

				#print SUMMARY"Genomic DNA: $genomic\n";
				print SUMMARY"$genomic\t";

				}
 		
 				if($mRNA_info=~/^mRNA:[\s\w]*\|([\w\W]*?)\s+([\s\w]*)\s*,\s*([\d]*)\s*bp/){
 				$mRNA=$1;
 				#print "mRNA: $mRNA\n";
 				print SUMMARY"$mRNA\n";

 				}
 		
 				if($mRNA_info=~/^Strand:\s*([minuspl]*)\s*$/){
 				$strand=$1;
 				#print "Strand: $strand\n";
 				}
 		
 				if($mRNA_info=~/^Number of exons:\s*([\d]*)\s*$/){
 				$exon_N=$1;
 				#print "Number of exons: $exon_N\n";
 				}

				if($mRNA_info=~/^Number of splicing sites:\s*([\d]*)\s*$/){
 				$splice_site=$1;
 				#print "Number of splice sites: $splice_site\n";
 				}
				
				if($mRNA_info=~/^mRNA coverage:\s*([\d]*)%\s*$/){
				$mRNA_coverage=$1;
 				#print "mRNA coverage: $mRNA_coverage\n";
 				}

				if($mRNA_info=~/^overall percent identity:\s*([\d\W]*)%\s*$/){
				$percent_identity=$1;
 				#print "percent_identity: $percent_identity\n";
 				}

				if($mRNA_info=~/^Missing mRNA ends:\s*([a-zA-Z]*)\s*$/){
				$missing_mRNA_ends=$1;
 				#print "Missing mRNA ends: $missing_mRNA_ends\n";
 				}

				#else{print"Could not parse line\n $mRNA_info\n Dont have any thing to match\n";}
				if($mRNA_info=~/^Exon/){
					for(my$i=1;$i<$exon_N+1;$i++){
						
						if($mRNA_info=~/Exon\s*(\d+)([\(\-\)\:]*?)([\s\w\d\W]*?)splice\s*site/){
       						#my$exon_in=$1;
       					my$currentexonnumber=$1;
        					my@exon_info=split(/\s+/,$3);
        					#print "@exon_info\n";
        					($exon_start{$currentexonnumber},$exon_end{$currentexonnumber})=split(/-/,$exon_info[1])if defined $exon_info[1];
       						($mRNA_start{$currentexonnumber},$mRNA_end{$currentexonnumber})=split(/-/,$exon_info[3])if defined $exon_info[3];
       						$exon_percent_identity{$currentexonnumber}=$exon_info[6]if defined $exon_info[6];
       						$exon_mismatch{$currentexonnumber}=$exon_info[8]if defined $exon_info[8];
 							$exon_gap{$currentexonnumber}=$exon_info[10]if defined $exon_info[10];
						#print "Exon $i Start:$exon_start{$i}\tExon $i End:$exon_end{$i}\n"
						#print SUMMARY"\tExon $currentexonnumber\t$exon_start{$currentexonnumber}\-$exon_end{$currentexonnumber}\n";	
        				}# if loop.				
				
					}# For loop.

			}
			
			
			next;
			}# foreach loop.
	
	
	# START for testing purposes only
	my@unsortedExonNumbers=keys(%exon_start);
	my@sortedExonNumbers=sort { $a <=> $b }@unsortedExonNumbers;
	
	print "\n\nExon co-ordinates for $mRNA:\n";
	foreach my$currentexonnumber(@sortedExonNumbers){
	print "Exon-start:$currentexonnumber\t$exon_start{$currentexonnumber}\-$exon_end{$currentexonnumber}\n";
	print SUMMARY"\tExon $currentexonnumber\t$exon_start{$currentexonnumber}\-$exon_end{$currentexonnumber}\n";	

	}
	
	
	
	# END for testing purposes only
	
	my@a= sort values(%exon_start);
	my@b= sort values(%exon_end);
	my@c= sort(@a,@b);
	
	my@sorted_c = sort { $a <=> $b } @c;
	@c=@sorted_c;
	my$l=@c;
	#print "\n$a[$l-1]\n";
	#print "@a";
	print SUMMARY "\n$mRNA\t$c[0] - $c[$l-1]\n";
	
	
	#print "\ngene_start=$exon_start{1}\tgene_end=$exon_end{$exon_N}";
	
	($gene{$mRNA})= extract_gene($c[0],$c[$l-1],$genomic,$strand,$mRNA);
	#print "$mRNA\t$c[0]\t$c[$l-1]\n";
	print GENE">Gene_$mRNA\n$gene{$mRNA}\n" if defined $gene{$mRNA} ;
	
	
	# extract upstream sequence if asked by the use usingoption  $opt_u
	if(defined $opt_u){
	$upstream{$mRNA}=extract_up($c[0],$c[$l-1],$genomic,$strand,$mRNA);
	print UP ">$mRNA $opt_u bases upstream sequence\n$upstream{$mRNA}\n";
	}
	
	# extraxt downstream sequences of asked by user using option $opt_d
	if(defined $opt_d){
	
	$downstream{$mRNA}=extract_down($c[0],$c[$l-1],$genomic,$strand,$mRNA);
	print DOWN ">$mRNA $opt_d bases downstream sequence\n$downstream{$mRNA}\n";

	}
	
	
	
	#print"\n\n";
	}# while loop.

print "Done....\n";
close(GENE);
close(SUMMARY);
close(FASTA);
#close(GENE);

# information collected: Genomic DNA=>$genomic,mRNA Name=>$mRNA,Strand=>$strand,Number of exons=>$exon_N,
# splice sites=>$splice_site,mRNA coverage=>$mRNA_coverage,Missing mRNA ends: $missing_mRNA_ends
# Exon start=>$exon_start{$i},Exon_end=>$exon_end{$i},mRNA start=>$mRNA_start{$i},
# mRNA end=>$mRNA_end{Si},$exon_percent_identity{$i},$exon_gap{$i}




}# End of subroutine spidey_parse

###########################################################################################
# Subroutine for the extraction of gene from the genomic DNA based on co-ordinates obtained
# from parsing spidey summary file. Save gene sequences in a file. Will try to align cDNA 
# with genomic DNA.

sub extract_gene{

	my($exon_start,$exon_end,$genomic,$strand,$mRNAname)=@_;
	chomp($exon_start,$exon_end,$genomic,$strand,$mRNAname);
	print "Extracting Gene\t$mRNAname\tco-ordinates:$exon_start,$exon_end,\ton molecule:$genomic,\tStrand:$strand\n\n";

	#print "infor received in subroutine extract_gene:\n$exon_start,$exon_end,$genomic,$strand\n";
	my($gene,$length)=();
	if($exon_start<$exon_end){
		$length=$exon_end-$exon_start+1;
		$exon_start=$exon_start-1;
		#print "\nFetching substring with co-ordinates:Start:$exon_start\tEnd:\t$exon_end\tLength:\t$length\n"; 

		$gene=substr($seq_hash{$genomic},$exon_start,$length);
	}

	elsif($exon_start>$exon_end){
		$length=$exon_start-$exon_end+1;
		$exon_start=$exon_end-1;
		#my $exon_end_N=$exon_start;
		#print "\nFetching substring with co-ordinates:Start:$exon_start_N\tEnd:\t$exon_start\tLength:\t$length\n"; 
		$gene=substr($seq_hash{$genomic},$exon_start,$length);
	}

	else{print"\nExon Start and end figures either are equal or not a numericl value\n";}

	if($strand eq 'minus'){
		$gene= reverse($gene);
		$gene=~tr/ATGCNatgcn/TACGNtacgn/;
		}
	return($gene);
	
	($exon_start,$exon_end,$length)=0;
	($gene,$genomic,$strand)=();

}

sub extract_down{
		
	my($exon_start,$exon_end,$down_start,$length)=0;
	my($downstream_sequence,$genomic,$strand,$mRNAname)=();

	($exon_start,$exon_end,$genomic,$strand,$mRNAname)=@_;
	chomp($exon_start,$exon_end,$genomic,$strand,$mRNAname);
	
	if($strand eq 'plus'){
		if(($exon_end  + $opt_d)>length($seq_hash{$genomic})){
			$down_start=$exon_end;
			$length=length($seq_hash{$genomic})-$exon_end;
		}
		else{
			$down_start=$exon_end;
			$length=$opt_d;
		}

		$downstream_sequence=substr($seq_hash{$genomic},$down_start,$length);
		
	}
	
	
	
	elsif($strand eq 'minus'){
		
		if(($exon_start - $opt_d)< 0){
			$down_start=0;
			$length=$exon_start;
		}
		else{
			$down_start=$exon_start - $opt_d-1; 
			$length=$opt_d;
		}

		$downstream_sequence=substr($seq_hash{$genomic},$down_start,$length);
		$downstream_sequence= reverse($downstream_sequence);
		$downstream_sequence=~tr/ATGCNatgcn/TACGNtacgn/;
	}
	
	
	
	print "Extracting downstream Sequence $mRNAname\tStart:$down_start\tEnd:".($down_start+$length)."\n";
	return($downstream_sequence);
	($exon_start,$exon_end)=0;
	($downstream_sequence,$genomic,$strand)=();


}


sub extract_up{
	
		
	my($exon_start,$exon_end,$up_start,$length)=0;
	my($upstream_sequence,$genomic,$strand,$mRNAname)=();

	($exon_start,$exon_end,$genomic,$strand,$mRNAname)=@_;
	chomp($exon_start,$exon_end,$genomic,$strand,$mRNAname);
	
	if($strand eq 'plus'){
		if(($exon_start - $opt_u)<0){
			$up_start=0;
			$length=$exon_start;
		}
		else{
			$up_start=$exon_start - 1 - $opt_u;
			$length=$opt_u;
		}

		$upstream_sequence=substr($seq_hash{$genomic},$up_start,$length);
		
	}
	
	
	
	elsif($strand eq 'minus'){
		
		if(($exon_end + $opt_u)> length($seq_hash{$genomic})){
			$up_start=$exon_end;
			$length=length($seq_hash{$genomic})-$exon_end;
		}
		else{
			$up_start=$exon_end; 
			$length=$opt_u;
		}

		$upstream_sequence=substr($seq_hash{$genomic},$up_start,$length);
		# reverse compliment the sequence.
		$upstream_sequence= reverse($upstream_sequence);
		$upstream_sequence=~tr/ATGCNatgcn/TACGNtacgn/;
	}
	
	print "Extracting upstream Sequence $mRNAname\tStart:$up_start\tEnd:".($up_start+$length)."\n";
	return($upstream_sequence);

	($exon_start,$exon_end)=0;
	($upstream_sequence,$genomic,$strand)=();

	
}
